

export enum MessageType {
  // COMMANDS
  CARD_POWER_ON_CMD= '62',
  CARD_POWER_OFF_CMD= '63',
  GET_SLOT_STATUS_CMD= '65',
  APDU_COMMAND_CMD= '6F',
  ESCAPE_COMMAND_CMD= '6B',
  // RESPONSES
  CARD_POWER_ON_RESP= '80',
  APDU_COMMAND_RESP= '80',
  CARD_POWER_OF_RESP= '81',
  GET_SLOT_STATUS_RESP= '81',
  NOTIFY_CARD_STATUS_COMMAND_RESP= '50',
  HARDWARE_ERROR_RESPONSE_RESP= '51',
  ESCAPE_COMMAND_RESP= '83'
}

