"Hello world sample, please remove"
type HelloWorldAfccReloader{
  "text"
  sn: String!  
}

type Query {
  "Hello world sample, please remove"
  getHelloWorldFromAfccReloader: HelloWorldAfccReloader
}

type Subscription {
  "Hello world sample, please remove"
  AfccReloaderHelloWorldSubscription: HelloWorldAfccReloader  
}